language: node_js
node_js:
  - lts/*
cache: npm
script:
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: dist
  github-token: ${GITHUB_TOKEN}
  committer_from_gh: true
  keep-history: true
  target_branch: gh-pages
  on:
    branch: master
